# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = PictureViewer
DESTDIR = ../x64/Debug
QT += core network gui widgets
CONFIG += c++11
DEPENDPATH += .
include(PictureViewer.pri)
win32:RC_FILE = PictureViewer.rc
